server:
  port: 3001

eureka:
  instance:
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://localhost:3000/eureka  ## 注册到 eureka

spring:
  application:
    name: boke_wjw  ## 应用程序名称，后面会在消费者中用到

  datasource:
    jdbc-url: jdbc:mysql://localhost:3306/crawler?characterEncoding=utf-8&serverTimezone=GMT%2B8&useSSL=true
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver

  thymeleaf:
    mode: LEGACYHTML5
    prefix: classpath:/templates/
    suffix: .html
    encoding: UTF-8
    cache: false
    servlet:
      content-type: text/html

mybatis:
  type-aliases-package: com.example.model
  mapper-locations: classpath:mapper/*.xml

