server:
  port: 3002

eureka:
  instance:
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://localhost:3000/eureka  ## 注册到 eureka

spring:
  application:
    name: boke_test ## 应用程序名称，后面会在消费者中用到

  datasource:
    jdbc-url: jdbc:mysql://localhost:3306/bokedb?characterEncoding=utf-8&serverTimezone=GMT%2B8&useSSL=true
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  type-aliases-package: com.example.model
  mapper-locations: classpath:mapper/*.xml